### ISSUE TITLE
Controller problem

### ISSUE THREAD

**Issue by RMAtK** [RossenX/NullDC-BEAR#11]
Everytime i start up mvc2 and hit start it brings me to the Dreamcast menu

**Comment by RossenX** [comment]
Hm, only 2 possible things i can think of that might cause that is:
1. Windows 10 for some reason sometimes sets your controller to player 2, without a player 1 which confuses SDL and makes all the buttons be held down, ez fix just restart/unplug or set your controller to player 1 for xinput.
2. The controller you're using doens't have proper mapping configs, ez fix just click the 'remap controller' button and do the on-screen instructinos.

**Comment by RMAtK** [comment]
Hmm everytime i fix it after an hour or so it does it again. any idea how to fix this

**Comment by RossenX** [comment]
Do you have any software that's changing your controller to be player 2, without there being a player 1? I know a couple of people with similar issue but usually fixed itself by setting the controller to player 1. On the controller list if it ends with #2 but there's no player 1 controller it can do that.

**Comment by RossenX** [comment]
Oh yeah also when you start nullDC (when this problem happens) could you look at the console and just note what it says "player 1 controller" and player 2 controller is? It has a text that says "player 1 using controller: <name>" Let me know if those match the one you set in BEAR, maybe there's a virtual hidden controller installed by something.

**Comment by RMAtK** [comment]
++BEARPlay: Port: 1 using Controller: ZEROPLUS P4 Wired Gamepad
++BEARPlay: Port: 2 using Keyboard.

**Comment by RMAtK** [comment]
Yeah i cant figure out what it is it's driving me crazy haha! Also thanks so much for gettin back to me on this. I'm really grateful for the hard work you put in.

**Comment by RMAtK** [comment]
https://gyazo.com/8cea473fe62b04484a5271c7a0974670

**Comment by RossenX** [comment]
Aight i've been racking my brain at a few things updated to a newer version of SDL, try that out and let me know how it goes. I know this one fixes several issues mostly with PS4 pads, but might fix your problem also.

**Comment by RossenX** [comment]
oh yeah you might need to do the 'remap controller' bit again.

**Comment by RossenX** [comment]
Hell yeah, for once i can say it wasn't my duct-taped code but SDL had some internal issue that were fixed in a not yet public build of it. Keep on kicking ass and have fun!

**Comment by RMAtK** [comment]
dude thank you soo much haah i really been itching to play with the homies! super stoked im loving it!

**Comment by RMAtK** [comment]
i lied it happens again HAH
