### ISSUE TITLE
i lied it happens again HAH

### ISSUE THREAD

**Issue by RMAtK** [RossenX/NullDC-BEAR#12]
i lied it happens again HAH

_Originally posted by @RMAtK in https://github.com/RossenX/NullDC-BEAR/issue_comments/708612761_

**Comment by RossenX** [comment]
God damn it, how about this: just copy the bear exe into a new folder, just the exe. and start it up so there's a fresh install of BEAR on there with none of the controls changed. Maybe you have some of the macros also bound to the start button?

**Comment by RMAtK** [comment]
hmm so just the exe? and install bear again? in the new folder? cuz i've tried uninstall reinstalling etc

**Comment by RossenX** [comment]
Aight updated 1.55 with a newest possible version of SDL i compiled myself, lets see if that helps you out. If not i might suggest x360ce to just remap your controller to a 360pad that should work i think.
