### ISSUE TITLE
FEATURE REQUEST: "Looking to play X"

### ISSUE THREAD

**Issue by Paxtez** [RossenX/NullDC-BEAR#13]
Currently there is are 3 statuses.  I was thinking it would be good if there was another one "LFG" or something, and then you would select a game.  Maybe it loads the game for single player and then if someone wants to they can challenge you and BEAR would auto-accept.

**Comment by RossenX** [comment]
Hey there thanks for playing BEAR! And that is on my TODO list i'm still finishing up the basics of the DC/Naomi stuff not started putting in the extra polish stuff yet, but playing Offline while waiting for a match then being able to be challanged to that game is on my TODO list.
