### ISSUE TITLE
Sammy Atomiswave Rom: Rumble Fish 2

### ISSUE THREAD

**Issue by Fu-Sung-Cookye** [RossenX/NullDC-BEAR#15]
"Rumble Fish 2" rom does not play or launch after the Naomi logo. Can somebody please look into this! To be more specific, this is the Rumble Fish 2 rom version provided via download interface of the Bear NullDC application that is not working correctly.

**Comment by RossenX** [comment]
Oh yeah on The Rumble Fish 2 doesn't work on nullDC, sorry.
It's in the downlaods because it's just part of the whole pack.

**Comment by Aslampervaiz** [comment]
Nulldc bear add new fba emulator plz

**Comment by Aslampervaiz** [comment]
Flycast generic joystick  not work plz sir all controller add

**Comment by RossenX** [comment]
> Flycast generic joystick not work plz sir all controller add

BEAR has nothing to do with flycast and fba emulator probably in the future right now working on adding mednafen.
