### ISSUE TITLE
dpad not being recognized

### ISSUE THREAD

**Issue by limmynade** [RossenX/NullDC-BEAR#16]
i did try remapping the controller, it sees the dpad then but I cant assign it to the joystick, I use dpad on fighting games so if there's a way to fix this, I would be grateful to know
I use a ds3 controller through scp toolkit so its shown as a xinput xbox 360 controller

**Comment by RossenX** [comment]
Hm odd if it recognizes it in the remap controller then it should work just fine. 
you can try one thing i can think of, in the BEAR folder there's a file called 'bearcontrollerdb.txt'
in there you'll see a text string of your controller configs as generated by the remapper.
Check if "dpleft/dpright/dpdown/dpup" should look something like this: dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2
check if that looks right. I had an issue with someone who's for w.e reason the decimal point was a comma. If it's a comma , replace it with a period .

Lemme know if this helps
