### ISSUE TITLE
control problem for other systems

### ISSUE THREAD

**Issue by MarLightning** [RossenX/NullDC-BEAR#19]
Hi Rossen. I really like your emulator NullDC-BEAR. It looks really great. 

I played Marvel vs Street Fighter on Saturn but control doesn't work. I tried everything including mapping a PS4 controller. it was still the same problem. Plus, there are no design for mapping for Saturn and other systems like NES and PlayStation. How can I fix that?

**Comment by RossenX** [comment]
To map any system that is no Naomi/Dreamcast do this:
1. Start the game you want to play
2. Make sure the window is ALL visible on the screen if it's not then go into the options->mednafen and make the window height/width lower. 
3. When you're in-game press alt + shift + 1
4. at the bottom you'll see gamepad: up (1) press up on your controller twice.
5. repeat 4 for all buttons until it says COMPLETE
6. Should be good to go then

**Comment by MarLightning** [comment]
I got it! Thanks. Also, I tried different systems like SNES and PS to set up buttons. It worked, too.  Wow, amazing. I would like to donate to you. Keep developing your NullDC Bear for better and adding more other systems like PS2, Nintendo 64, and Xbox, so we play online.

**Comment by Bundesliga420** [comment]
Hi Rossen, got a problem with the joysticks, i got a usb adapter for ps2 joy, null recognize them, but cant remap or do any thing with them, i press buttons and do nothing. Any idea? Thanks and sorry for my english.

**Comment by Guil07** [comment]
Hello, if you know, could you tell me how to drop the controller to other players in an online game?
