### ISSUE TITLE
Crashy McCrashface

### ISSUE THREAD

**Issue by ChocoBadger** [RossenX/NullDC-BEAR#20]
Found this error while trying to install NullDC-BEAR on Windows 10, was wondering if someone wouldn't mind taking a look at it please and thank you! :)
![RossenX Error](https://user-images.githubusercontent.com/78290474/106375019-694e2b80-6356-11eb-8c27-ce1365327d01.png)

**Comment by RossenX** [comment]
There's usually a file called "gagged.users" that is generated if you gag/block someone. Looks like it found it when it asked for it but then couldn't find it when it tried to read it. Maybe check if some antivirus is blocking BEAR from reading files, if you have avast or AVG those have been known to cause all kinda weirdness, add the BEAR folder to exceptions with those two.
