### ISSUE TITLE
Feature Request: New Dreamcast Controller/Arcade Stick Binding for Taunt via A + Start

### ISSUE THREAD

**Issue by tjh3** [RossenX/NullDC-BEAR#21]
Add a Dreamcast binding for light kick + start (A button + Start button). It's how you taunt in some games (e.g. Marvel vs Capcom 2).

You currently have (X+A), (Y+B), (C+Z), (X+Y), (Y+Z), (A+B), (B+C), (X+Y+Z), and (A+B+C) ... but no (A+Start).

![image](https://user-images.githubusercontent.com/52579312/106376938-44ee5100-634e-11eb-8a3d-6c5ed7b94f9e.png)

**Comment by RossenX** [comment]
Sounds like a fair request, i'll update this when i added it.

**Comment by ThiGhisleri** [comment]
Add a Dreamcast binding for (Y+B) too. It's a move for storm and wolverine on Marvel vs Capcom 2

**Comment by RossenX** [comment]
Sure i just finished some other macro code i cna add some more macros to the list, just gimme a lil time.
