### ISSUE TITLE
Is this a false positive?

### ISSUE THREAD

**Issue by MasterKwonKaichi** [RossenX/NullDC-BEAR#23]
![image](https://user-images.githubusercontent.com/73682160/108028983-a9582280-7067-11eb-9103-271900100d4e.png)

Can someone verify that this is a false positive?

**Comment by RossenX** [comment]
That’s not a detection. It’s their AI guessing that it’s unsafe. Which is fair enough since it’s an exe that unpacks other exes out of itself and whatnot. But yeah some AI “guess” that it’s unsafe. But nah you’re fine there’s nothing in bear i run scans on it before each upload also just in case.

**Comment by MasterKwonKaichi** [comment]
> That’s not a detection. It’s their AI guessing that it’s unsafe. Which is fair enough since it’s an exe that unpacks other exes out of itself and whatnot. But yeah some AI “guess” that it’s unsafe. But nah you’re fine there’s nothing in bear i run scans on it before each upload also just in case.

Thanks, sorry I can't read crap, didn't knew that the detection was just a guess. Sorry about that.
