### ISSUE TITLE
Feature Request: Score Counter Next to Player Names

### ISSUE THREAD

**Issue by Paxtez** [RossenX/NullDC-BEAR#24]
It would be nice if there was an option to have a score counter next to the each player and a global keybind for incrementing / resetting the scores.  Would be useful for keeping track of scores in games that don't do it or in arcade modes.

Thanks for the awesome program!

**Comment by RossenX** [comment]
That's a nice idea! I think i had that in my todo list a while back but got distracted by other stuff.
It would only be possible on Naomi/Dreamcast games since those are the only ones i custom code the inputs for, so if you mean those games then yeah totally doable.
