### ISSUE TITLE
HD/4K options

### ISSUE THREAD

**Issue by Mkhan73** [RossenX/NullDC-BEAR#26]
Hi,
I've seen a few youtube videos of people playing MVC2 or CVSNK2 in 4k. How do I enable this on NullDC BEAR as i cant seem to find an option where i can select this/
Thanks

**Comment by RossenX** [comment]
You don't` need to do anything to get it to 4k, the window will render at whatever size you maximize it to. It auto scales up to w.e resolution the window is.

**Comment by Mkhan73** [comment]
Thanks RossenX, i thought it looked crisper but was had to tell on a laptop screen. I have used most other dreamcast emulators but this one is the best.
