### ISSUE TITLE
Controller problems

### ISSUE THREAD

**Issue by mutedknight** [RossenX/NullDC-BEAR#27]
I know someone else ran into the same issue: the nulldc emulator doesn't read any inputs but the start button, which goes to the main menu every time the game is loaded. I've tried multiple controllers and different installations as well. I'm really confused about what I should do next, and I'd really like to play some Soulcalibur.

**Comment by RossenX** [comment]
That's a known weird but where for some reason windows on xinput devices reports that all the buttons are being held down for some reason. Still havn't figured out why, but a simple restart of the PC will fix that problem.

**Comment by mutedknight** [comment]
For some reason, that fixed it even though I've restarted my computer multiple times as this has been an issue for the past two days.
