### ISSUE TITLE
Matchmaking server down?

### ISSUE THREAD

**Issue by slagfart** [RossenX/NullDC-BEAR#3]
A friend and me are in the lobby, but can't see each other. We both appear in an empty lobby. See pic here: https://github.com/slagfart/pics/blob/master/bear.png

Any ideas?

**Comment by RossenX** [comment]
There is no matchmaking server, BEAR is a standalone application and as long as two PCs can connect to eachother they can play. If you want to play online for example you'll need some sort of VPN that will allow both PCs to have direct connection to eachother. Most people use Radmin VPN which is free and works very well, you can setup a network or join existing networks for people.
If you got any more questions hit me up on the CVS2 or FGCArcadia Discord:
CVS2: https://discordapp.com/invite/0eFue7vlvpsc0HXi
FGCArcadia: https://discord.gg/qzYWCr
