### ISSUE TITLE
CRASH:  NullDC Bear will crash if closing or disabling RADMIN VPN First

### ISSUE THREAD

**Issue by Paxtez** [RossenX/NullDC-BEAR#33]
Most in the title, but most of the time if I close or turn off RADMIN VPN I get a crash from NullDC Bear.

This isn't during a match, but just on the "who is online" screen.

Let me know if a crash report is needed.

**Comment by RossenX** [comment]
Oh, well if you get some crash report specially from crasy mccrashface that would be useful, generally even if you have radmin turned off all it does is send a 'who is' request on whoever is on the LAN, shouldn't crash but if you got a report i'd like to see it yus.
