### ISSUE TITLE
NullDC.BEAR crashes, if i go into the Mednafen options and try to click on any emulator

### ISSUE THREAD

**Issue by ProhorovIlja** [RossenX/NullDC-BEAR#36]
**Whenever I'm going into the Mednafen options and try to click on any emulator (console), that is in this menu, I'm getting this error.**

![Desktop Screenshot 2021 08 07 - 13 00 45 15](https://user-images.githubusercontent.com/47087189/128596535-1d76aaee-2db9-4dfe-9039-fac790d3e247.png)

**Comment by RossenX** [comment]
oh hm looks like maybe your system uses a comma instead of a period as a decimal point which mednafen does not like.
