### ISSUE TITLE
It's very hard to use skills like 6246a， 623a or 624624a

### ISSUE THREAD

**Issue by ctdhm1984** [RossenX/NullDC-BEAR#4]
Hello!
We are kof XI players.
It's very hard to use skills like 6246a， 623a or 624624a，by joystick（BlueFlame v2.0/Qanba Obsidian Arcade Joystick）.
We guess that the reasons are  maple plugins，maybe keymapping in bearlauncher.
So would you support more maple plugins,like "qkoJAMMAMaple_Win32.dll" or "PuruPuru_win32.dll".That may works better.
                                    Thanks!

**Comment by RossenX** [comment]
Nah i didn't want there to be a chat since it's meant to promote a community use of it for discords and other chat applications, don't wanna get rid of the community aspect of fighting games since it's the most important part.
