### ISSUE TITLE
Controller mapping doesn't work

### ISSUE THREAD

**Issue by EuroNotus** [RossenX/NullDC-BEAR#40]
I'm using a hori fighting octa, trying to play MVC2, not sure why it doesn't work right. It won't register any control mapping changes in game, even if it says it saved them, and the start button only opens the emulator settings. I've tried the remap controller button, reinstalling, restarting my computer, I just can't get it to work right. Any help would be much appreciated.

**Comment by RossenX** [comment]
Heyo! I'm aware of the mapping issue i'm redoing a lot of the mapping stuff for the next update.
There's an SDL difference between Flycast and BEAR right now, it'll be sorted next update for now you can go in Flycast. press TAB go to settings->controls and set them up from there like you would on a standalone version of Flycast.

**Comment by EuroNotus** [comment]
Maybe I'm stupid for not thinking of that, but thank you so much.
