### ISSUE TITLE
Xinput are messed up

### ISSUE THREAD

**Issue by KuroRaiden** [RossenX/NullDC-BEAR#42]
Flycast BEAR v1.0-238-g773a00d8b

When mapping inputs for on hitbox in xinput mode, RT/LT and Select all reads as the same button (button 4), buttons mapping are labeled different ( RB now being labeled as button 10). Was working perfectly fine in yesterday build, is there any way to roll the input mapper back or hopefully this issue is resolved soon in the next nightly. 
PS3/PS4/Switch mode also does not register in Flycast BEAR.
![image](https://user-images.githubusercontent.com/60013344/134746499-9460b206-fc26-45ce-8680-07d59cf09b7b.png)

**Comment by KuroRaiden** [comment]
Added: RT only register inputs on release.

**Comment by KuroRaiden** [comment]
Added: Razer Panthera is not registering or showing up in the program, so I assume that all Dinputs are not currently support in this update

**Comment by RossenX** [comment]
You don’t need to go i to flycast for buttons anymore. Go to the controls panel on bear and click “remap controller” and go through the button check and you should be fine on anything button related. Panthera should work fine also i’ve tried out dinput and xinput and they should be working. Just go through the automated setup as shown in the github page for buttons.

**Comment by KuroRaiden** [comment]
Alright will try that and get back with you shortly

**Comment by KuroRaiden** [comment]
everything is working great, thanks!
