### ISSUE TITLE
I can't install the emulator

### ISSUE THREAD

**Issue by Jesus7892** [RossenX/NullDC-BEAR#43]
When I try to install the exe, a window appears saying that I cannot unzip the emulator because I have denied access to the path awbios.zip in flycast folder
![Sin fwfwfw](https://user-images.githubusercontent.com/91973736/136063123-4df58f1f-a534-47d2-a8e9-264b56ee795f.png)

**Comment by RossenX** [comment]
Probably windows or antivirus blocking BEAR from extracting the files correctly. Try adding an exception in your antivirus for BEAR. or turn it off if you do not know how to add exception.
