### ISSUE TITLE
Instant crashing after fresh install

### ISSUE THREAD

**Issue by KnightoftheWind3** [RossenX/NullDC-BEAR#44]
I get this message after a fresh install. It said to send this to you so here you go,
![error](https://user-images.githubusercontent.com/92240883/136681737-98090c86-5767-44ff-a5d4-8b85c7dd2089.png)

**Comment by RossenX** [comment]
That looks like the port that BEAR uses is being used by something else. Check if anything is using port 8002. Probably a restart will solve it.
