### ISSUE TITLE
PS games not working

### ISSUE THREAD

**Issue by FLAMINGclar** [RossenX/NullDC-BEAR#47]
I tried downloading PS games in the free dlc tab and nothing will go through saying its a server error. Is this just me or is this everyone with the newest update or anything im unaware of currently with the emulator.

**Comment by RossenX** [comment]
Heyo, No it's not just you don't worry. The website i was using for PS games has taken them down so it'll be sorted very soon with a new host.

**Comment by predadorBR** [comment]
tenho a solução

**Comment by predadorBR** [comment]
[PSX.zip](https://github.com/RossenX/NullDC-BEAR/files/15191500/PSX.zip)
