### ISSUE TITLE
Z-Axis button only activates on release after mapping

### ISSUE THREAD

**Issue by wokyen** [RossenX/NullDC-BEAR#5]
First off, thanks for making this and building something awesome for free!

Sorry if this has been brought up or addressed, but I was just wondering if there was a way around mapping for XInput controllers for axis-based triggers.

Thanks again!

![image](https://user-images.githubusercontent.com/43803331/91377141-91e45f00-e7d3-11ea-9ebb-6a5023e73b4c.png)

**Comment by RossenX** [comment]
Oh that just means you need to click the calibrate button at the center of up/down/left/right.
I tried to make it recognize every type of input so it works for all sticks/controllers, but some do need calibration so BEAR knows what inputs to look for.
