### ISSUE TITLE
Chat

### ISSUE THREAD

**Issue by mkultimate** [RossenX/NullDC-BEAR#6]
To begin with, I congratulate you for the excellent work you have done to be able to play online these games that remind us of the times that were played in the arcades and to see him play online with any player from all over the world. float with transparency mode that when pressing the letter T is activated transparency style or in the way you think is best, this would be great.

**Comment by RossenX** [comment]
BEAR is more meant to be a tool to be used by the community i don't want to add chat to it since it would retract from discord and other community places.
