### ISSUE TITLE
ZeroTier compatibility

### ISSUE THREAD

**Issue by dtoured** [RossenX/NullDC-BEAR#9]
After playing through Radmin for some time now, we started experiencing connectivity and ping issues region-wide and we were thinking of mirroring our network through ZeroTier to have a functional backup. After trying a bunch of times already we can't get to see each other on BEAR's lobby. I was wondering if the program is indeed compatible with ZeroTier in the first place and if there's something we can do to be able to connect to one another.

Just to clarify we tried uninstalling Radmin to see if that was an issue but we had no luck that way either and ZeroTier does work outside of BEAR.

**Comment by RossenX** [comment]
I never tried it personally but i know some people do use zerotier and hamachi over Radmin that got it to work.
BEAR will work on anything that allows UDP(8002) for lobby and TCP(Whatever port you pick in BEAR) for gameplay. It should work.

**Comment by dtoured** [comment]
Is there a way to force BEAR to choose a network adapter over another? That way we could start ruling out problems more easily

**Comment by RossenX** [comment]
It uses any adapter that it finds, it literally sends a udp call to any PC it finds.
Though i just read that zerotier does not allow udp/tcp on most ports by default and you'd need to open them.
https://www.zerotier.com/manual/
Should help.
